### ISSUE TITLE
Questions and answers with common css.

### ISSUE THREAD

**Issue by wenzhixin** [wenzhixin/blog#11]
Q: How to turn off number input spinners?

A: WebKit desktop browsers add little up down arrows to number inputs called spinners.We can turn them off visually like this:
```css
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
    -webkit-appearance: none; 
    margin: 0; 
}
```
